### PR TITLE
Memory leak fix in decorator implementation.

### PR DESCRIPTION
**Pull request by SethDavenport**
Fix for https://github.com/angular-redux/example-app/issues/34, thanks to @aminpaks for the fix.  Reconstituted from  angular-redux/store#409, with an additional commit from me to remove unintentionally-committed build output.

### CODE REVIEW

**Comment by DcsMarcRemolt** [comment]
Just fyi, this change broke tests in my application. I was subscribing to a @select decorator of a component inside the tests, firing actions and testing if the state changes correctly via selector.

As a good citizen I reset the store and everything else before every test. 

This setup now breaks as the observable (var result) is cached at "compile time" (I know there is not real compile time in JS) hard binding to the initial store ignoring the swapping out of the store in my tests.

I worked around this by using store.select() instead of the decorator. 

This should imho have been a breaking change, not a patch level one.

**Comment by SethDavenport** [comment]
see issue #413

**Comment by DcsMarcRemolt** [comment]
Didn't see that one, sorry. Thanks for the hint!

**Comment by SethDavenport** [comment]
No worries - it wasn't _supposed_ to be a breaking change 😳 

I've released 6.4.2 which fixes the regression.

**Pull request merged**
