### PR TITLE
feat: Introduced a new function called provideStore() which accepts a already created Redux store

### PR DESCRIPTION
**Pull request by drager**
Hey, thanks for a great library!

This pull request brings an suggestion to NgRedux and I just want to explain why I think this is a good idea. 

I come mainly from the react community side when using Redux, and there I have been using this library called `react-redux` which I also think is great. So when using that library I wrote the stores like I would do just using Redux and then pass the store down to react-redux which then solved all the rest for me. So basically this is the desired behavior I want to get from NgRedux as well. I even have some stores created in my React applications that I would like to just copy and paste to reuse in my Angular project. So this is what this pull request brings to NgRedux. A function that accepts a already created Redux store so the users can themselves create a store how they want to do it.

This new function does not break anything old, like `configureStore()`.

I also created a new function `private setStore(store: Store<RootState>) {}` which is called by `configureStore()` and `provideStore()`.

I updated the README and CHANGELOG as well.

Let me know what you think, @e-schultz @SethDavenport. Thanks!

### CODE REVIEW

**Comment by drager** [comment]
Is it possible to get your thoughts on this? @e-schultz @SethDavenport  @wbuchwalter 

Would be great if this could get merged if you want it in the package.

**Comment by wbuchwalter** [comment]
👍 
That's something I always wanted to do in `ng-redux` (for angular 1) but there was no clean way to do it.
It's also useful when you have `react` and `angular` coexisting in an app. You can create the store in the react section and pass it to `ngRedux`.

I don't have time to review the code (and I'm not qualified to do that anymore anyway 😃  ), so will let others decide to merge or not.

**Comment by e-schultz** [comment]
@drager I recall seeing this request come up for ng-redux for Angular 1. I'll take a closer look at this soon and provide feedback, but at initial quick glance it's looking good.

On the road right now so might not be able to give it full attention until I return next week, but really appreciate the contribution.

Thanks,

Evan

**Comment by drager** [comment]
@wbuchwalter: Great that someone else also thought of it.

@e-schultz: Alright, great. Just ping when you have looked closely. Thanks!

**Comment by danielfigueiredo** [comment]
👍 
I just ran into the same issue, the connector should accept being bootstrapped with an existing store. Otherwise you don't have access outside angular context to the store that is managed by NgRedux

**Comment by drager** [comment]
@danielfigueiredo: Yes, exactly. I would want to something like this if that were possible (What I'm doing in react). Using the redux-persist library.

```js
persistStore(store, {}, () => {
  ...
})
```

**Comment by SethDavenport** [comment]
Also on the road but this makes sense. NgRedux.configureStore is easier for redux newcomers to grok and also allows you write your own middlewares and enhancers that use DI

However the new provideStore allows for flexibility for other use cases, so :+1:

**Comment by SethDavenport** [comment]
Hey @drager Evan just pushed out 3.2.0 with this feature. Thanks for the contribution, and sorry for the delay. We've both been travelling a lot recently.

**Comment by drager** [comment]
@e-schultz, @SethDavenport: Great. thanks!

**Comment by maheshnvv** [comment]
When I use providestore(store) with a store configured to use redux dev tool extension, The time travel is not getting reflected in the UI. But when I used configurestore with devToolExtension class to configure works perfectly.

Is there any way to get the time travel works fine if I use providestore  ?

**Pull request merged**
